name: Test
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pixi CLI
              run: |
                  curl -fsSL https://pixi.sh/install.sh | sh
                  export PATH="/home/runner/.pixi/bin:$PATH"

            - name: Install dependencies and build
              run: |
                  export PATH="/home/runner/.pixi/bin:$PATH"
                  pixi install --locked

            - name: Run lint - pixi run lint
              run: |
                  export PATH="/home/runner/.pixi/bin:$PATH"
                  if pixi run lint 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi

            - name: Run tests - pixi run t
              run: |
                  export PATH="/home/runner/.pixi/bin:$PATH"
                  pixi run t

            - name: Run examples - pixi run examples
              run: |
                  export PATH="/home/runner/.pixi/bin:$PATH"
                  pixi run examples

