name: Test
on: [push, pull_request]
jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, ubuntu-24.04-arm, macos-14]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Pixi
              uses: prefix-dev/setup-pixi@v0.10.1
              with:
                  pixi-version: v0.80.0
                  cache: true
                  locked: true

            - name: Check formatting
              run: |
                  pixi run lint
                  git diff --exit-code

            - name: Run tests
              run: pixi run t

            - name: Run examples
              run: pixi run examples

            - name: Build package
              run: pixi publish --path . --target-dir dist
